package com.ftiger.www.game.mysql.entity;

public class User extends UserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NICK_NAME
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.AVATAR
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gold
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    private Long gold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NICK_NAME
     *
     * @return the value of user.NICK_NAME
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NICK_NAME
     *
     * @param nickName the value for user.NICK_NAME
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.AVATAR
     *
     * @return the value of user.AVATAR
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.AVATAR
     *
     * @param avatar the value for user.AVATAR
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gold
     *
     * @return the value of user.gold
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    public Long getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gold
     *
     * @param gold the value for user.gold
     *
     * @mbg.generated Tue Apr 24 22:22:14 CST 2018
     */
    public void setGold(Long gold) {
        this.gold = gold;
    }
}